name: Build

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        id: install
        run: npm ci

      - name: Build
        id: build
        run: npm run build
