#!/usr/bin/env python3
"""
Emit a plain AWS CLI shell script that creates or updates a Step Functions
state machine. Useful for one-off deployments, CI pipelines without an IaC
tool, or smoke-testing a freshly authored ASL.

The emitter writes three files: a deploy.sh, the ASL file, and an inline IAM
policy document. Substitutions (${Placeholder}) in the ASL are handled via
envsubst on a copy of the file before upload.

Usage:
    python scripts/deploy/emit_cli.py \
        --asl path/to/workflow.asl.json \
        --name my-state-machine \
        --type STANDARD \
        --outdir cli/
"""
from __future__ import annotations

import argparse
import json
import os
import re
import stat
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(_HERE, "..")))

import _infer_iam  # noqa: E402


_DEPLOY_SH = r"""#!/usr/bin/env bash
# Generated by aws-step-functions-jsonata skill. Review before running.
set -euo pipefail

NAME="{name}"
TYPE="{sfn_type}"
REGION="${{AWS_REGION:-$(aws configure get region)}}"
ROLE_NAME="${{NAME}}-execution-role"
LOG_GROUP="/aws/vendedlogs/states/${{NAME}}"
ASL_FILE="{asl_basename}"
POLICY_FILE="policy.json"

# -------------------------------------------------------------------
# Step 1: placeholder substitution
# -------------------------------------------------------------------
# Set these before running if your ASL has any ${{Placeholder}} tokens:
{env_exports}

RENDERED_ASL="$(mktemp)"
trap 'rm -f "$RENDERED_ASL"' EXIT
envsubst < "${{ASL_FILE}}" > "${{RENDERED_ASL}}"

# -------------------------------------------------------------------
# Step 2: create IAM role (idempotent)
# -------------------------------------------------------------------
if ! aws iam get-role --role-name "${{ROLE_NAME}}" >/dev/null 2>&1; then
  aws iam create-role --role-name "${{ROLE_NAME}}" \
    --assume-role-policy-document '{{"Version":"2012-10-17","Statement":[{{"Effect":"Allow","Principal":{{"Service":"states.amazonaws.com"}},"Action":"sts:AssumeRole"}}]}}'
  # IAM is eventually consistent — wait a beat for propagation
  sleep 10
fi

aws iam put-role-policy --role-name "${{ROLE_NAME}}" \
  --policy-name "${{NAME}}-inline" \
  --policy-document "file://${{POLICY_FILE}}"

ROLE_ARN=$(aws iam get-role --role-name "${{ROLE_NAME}}" --query Role.Arn --output text)

# -------------------------------------------------------------------
# Step 3: create log group (idempotent)
# -------------------------------------------------------------------
aws logs create-log-group --log-group-name "${{LOG_GROUP}}" 2>/dev/null || true
aws logs put-retention-policy --log-group-name "${{LOG_GROUP}}" --retention-in-days 14
LOG_GROUP_ARN="arn:aws:logs:${{REGION}}:$(aws sts get-caller-identity --query Account --output text):log-group:${{LOG_GROUP}}:*"

# -------------------------------------------------------------------
# Step 4: create or update the state machine
# -------------------------------------------------------------------
LOGGING_CFG=$(cat <<EOF
{{"level":"ALL","includeExecutionData":true,"destinations":[{{"cloudWatchLogsLogGroup":{{"logGroupArn":"${{LOG_GROUP_ARN}}"}}}}]}}
EOF
)

if EXISTING=$(aws stepfunctions list-state-machines --query "stateMachines[?name=='${{NAME}}'].stateMachineArn" --output text); [ -n "$EXISTING" ]; then
  echo "updating ${{EXISTING}}"
  aws stepfunctions update-state-machine \
    --state-machine-arn "${{EXISTING}}" \
    --definition "file://${{RENDERED_ASL}}" \
    --role-arn "${{ROLE_ARN}}" \
    --logging-configuration "${{LOGGING_CFG}}" \
    --tracing-configuration enabled=true
  echo "ARN=${{EXISTING}}"
else
  echo "creating ${{NAME}}"
  aws stepfunctions create-state-machine \
    --name "${{NAME}}" \
    --type "${{TYPE}}" \
    --definition "file://${{RENDERED_ASL}}" \
    --role-arn "${{ROLE_ARN}}" \
    --logging-configuration "${{LOGGING_CFG}}" \
    --tracing-configuration enabled=true \
    --query stateMachineArn --output text
fi
"""


def _find_placeholders(asl_text: str) -> list[str]:
    pat = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")
    return sorted(set(pat.findall(asl_text)))


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--asl", required=True)
    ap.add_argument("--name", required=True)
    ap.add_argument("--type", default="STANDARD", choices=["STANDARD", "EXPRESS"])
    ap.add_argument("--outdir", required=True)
    args = ap.parse_args(argv)

    with open(args.asl) as f:
        asl_text = f.read()
    doc = json.loads(asl_text)

    os.makedirs(args.outdir, exist_ok=True)
    asl_basename = os.path.basename(args.asl)
    with open(os.path.join(args.outdir, asl_basename), "w") as f:
        f.write(asl_text)

    # Policy
    policy = _infer_iam.infer_policy(doc)
    for stmt in policy.get("Statement", []):
        stmt.pop("Comment", None)
        stmt["Action"] = [a for a in stmt["Action"] if not a.startswith("#")]
    with open(os.path.join(args.outdir, "policy.json"), "w") as f:
        json.dump(policy, f, indent=2)

    # Placeholder env exports (as comments)
    placeholders = _find_placeholders(asl_text)
    if placeholders:
        env_exports = "\n".join(f"# export {p}='...'" for p in placeholders)
    else:
        env_exports = "# (no placeholders detected in ASL)"

    sh = _DEPLOY_SH.format(
        name=args.name,
        sfn_type=args.type,
        asl_basename=asl_basename,
        env_exports=env_exports,
    )
    sh_path = os.path.join(args.outdir, "deploy.sh")
    with open(sh_path, "w") as f:
        f.write(sh)
    os.chmod(sh_path, os.stat(sh_path).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f"wrote {sh_path}")
    print(f"wrote {os.path.join(args.outdir, 'policy.json')}")
    print(f"wrote {os.path.join(args.outdir, asl_basename)}")
    if placeholders:
        print(f"export these before running deploy.sh: {', '.join(placeholders)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
