#!/usr/bin/env python3
"""
Emit a SAM template that deploys a Step Functions state machine.

SAM is the shortest path when the rest of the project is SAM-based. Uses
AWS::Serverless::StateMachine with DefinitionUri pointing at the ASL file
and DefinitionSubstitutions for placeholder injection.

Usage:
    python scripts/deploy/emit_sam.py \
        --asl path/to/workflow.asl.json \
        --name MyStateMachine \
        --type STANDARD \
        --outdir sam/
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(_HERE, "..")))

import _infer_iam  # noqa: E402


_TEMPLATE = """# Generated by aws-step-functions-jsonata skill.
# Build with: sam package / sam deploy — plain `aws cloudformation deploy`
# will NOT resolve DefinitionUri for a local path.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: {name} state machine (JSONata)

Parameters:
{parameter_block}

Resources:
  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/{name}
      RetentionInDays: 14

  {name}:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: {asl_basename}
      Type: {sfn_type}
      DefinitionSubstitutions:
{substitution_block}
      Tracing:
        Enabled: true
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroup.Arn
      Policies:
        - Statement:
{statement_block}

Outputs:
  StateMachineArn:
    Value: !Ref {name}
"""


def _find_placeholders(doc: dict) -> list[str]:
    pat = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")
    tokens = set()

    def walk(o):
        if isinstance(o, str):
            tokens.update(pat.findall(o))
        elif isinstance(o, dict):
            [walk(v) for v in o.values()]
        elif isinstance(o, list):
            [walk(v) for v in o]

    walk(doc)
    return sorted(tokens)


def _yaml_list(items: list[str], indent: int) -> str:
    pad = " " * indent
    return "\n".join(f"{pad}- {json.dumps(i)}" for i in items)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--asl", required=True)
    ap.add_argument("--name", required=True)
    ap.add_argument("--type", default="STANDARD", choices=["STANDARD", "EXPRESS"])
    ap.add_argument("--outdir", required=True)
    args = ap.parse_args(argv)

    with open(args.asl) as f:
        doc = json.load(f)

    os.makedirs(args.outdir, exist_ok=True)
    asl_basename = os.path.basename(args.asl)
    with open(os.path.join(args.outdir, asl_basename), "w") as f:
        json.dump(doc, f, indent=2)

    placeholders = _find_placeholders(doc)
    if placeholders:
        parameter_block = "\n".join(
            f"  {p}:\n    Type: String\n    Description: Fill in — referenced by ${{{p}}} in ASL"
            for p in placeholders
        )
        substitution_block = "\n".join(f"        {p}: !Ref {p}" for p in placeholders)
    else:
        parameter_block = "  # (no substitutions detected)\n  Dummy:\n    Type: String\n    Default: unused"
        substitution_block = "        Dummy: unused"

    # Build inline Statements list for Policies[0].Statement
    policy = _infer_iam.infer_policy(doc, include_logging=False, include_xray=False)
    stmts = []
    for stmt in policy["Statement"]:
        actions = [a for a in stmt.get("Action", []) if not a.startswith("#")]
        if not actions:
            continue
        stmts.append({
            "Effect": stmt.get("Effect", "Allow"),
            "Action": actions,
            "Resource": stmt.get("Resource", "*"),
        })

    statement_lines: list[str] = []
    for s in stmts:
        statement_lines.append(f"          - Effect: {s['Effect']}")
        statement_lines.append(f"            Action:")
        for a in s["Action"]:
            statement_lines.append(f"              - {json.dumps(a)}")
        statement_lines.append(f"            Resource: {json.dumps(s['Resource'])}")

    out = _TEMPLATE.format(
        name=args.name,
        asl_basename=asl_basename,
        sfn_type=args.type,
        parameter_block=parameter_block,
        substitution_block=substitution_block,
        statement_block="\n".join(statement_lines) if statement_lines else "          []",
    )

    out_path = os.path.join(args.outdir, "template.yaml")
    with open(out_path, "w") as f:
        f.write(out)

    print(f"wrote {out_path}")
    print(f"wrote {os.path.join(args.outdir, asl_basename)}")
    print("deploy with: sam build && sam deploy --guided")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
