#!/usr/bin/env python3
"""
Emit a CDK (TypeScript) scaffold using aws-stepfunctions L1 CfnStateMachine.

We use L1 rather than the high-level StateMachine + DefinitionBody.fromFile
because L1 supports DefinitionSubstitutions (string placeholders resolved at
deploy time) — the high-level construct does not, and its chainable builder
is irrelevant when the ASL is authored externally.

Usage:
    python scripts/deploy/emit_cdk.py \
        --asl path/to/workflow.asl.json \
        --name MyStateMachine \
        --type STANDARD \
        --outdir cdk/lib/
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(_HERE, "..")))

import _infer_iam  # noqa: E402


_TS_TEMPLATE = r"""// Generated by aws-step-functions-jsonata skill. Review before deploying.
import * as path from 'path';
import * as fs from 'fs';
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as sfn from 'aws-cdk-lib/aws-stepfunctions';

export interface %CLASS%Props extends cdk.StackProps {
  /** Fill in once per ${Placeholder} referenced in the ASL. */
%PROPS%
}

export class %CLASS% extends cdk.Stack {
  public readonly stateMachineArn: string;

  constructor(scope: Construct, id: string, props: %CLASS%Props) {
    super(scope, id, props);

    const aslPath = path.join(__dirname, '%ASL%');
    const definitionString = fs.readFileSync(aslPath, 'utf8');

    const logGroup = new logs.LogGroup(this, 'LogGroup', {
      // /aws/vendedlogs/states/* bypasses the 5120-char resource-policy cap
      logGroupName: '/aws/vendedlogs/states/%NAME%',
      retention: logs.RetentionDays.TWO_WEEKS,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    const role = new iam.Role(this, 'ExecutionRole', {
      assumedBy: new iam.ServicePrincipal('states.amazonaws.com'),
    });
%POLICY%

    const machine = new sfn.CfnStateMachine(this, '%NAME%', {
      stateMachineName: '%NAME%',
      stateMachineType: '%TYPE%',
      roleArn: role.roleArn,
      definitionString,
      definitionSubstitutions: {
%SUBS%
      },
      loggingConfiguration: {
        level: 'ALL',
        includeExecutionData: true,
        destinations: [{
          cloudWatchLogsLogGroup: { logGroupArn: logGroup.logGroupArn },
        }],
      },
      tracingConfiguration: { enabled: true },
    });

    this.stateMachineArn = machine.attrArn;
    new cdk.CfnOutput(this, 'StateMachineArn', { value: machine.attrArn });
  }
}
"""


def _find_placeholders(doc: dict) -> list[str]:
    pat = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")
    tokens: set[str] = set()

    def walk(o):
        if isinstance(o, str):
            tokens.update(pat.findall(o))
        elif isinstance(o, dict):
            [walk(v) for v in o.values()]
        elif isinstance(o, list):
            [walk(v) for v in o]

    walk(doc)
    return sorted(tokens)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--asl", required=True)
    ap.add_argument("--name", required=True)
    ap.add_argument("--type", default="STANDARD", choices=["STANDARD", "EXPRESS"])
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--class-name", default=None)
    args = ap.parse_args(argv)

    with open(args.asl) as f:
        doc = json.load(f)

    os.makedirs(args.outdir, exist_ok=True)
    asl_basename = os.path.basename(args.asl)
    with open(os.path.join(args.outdir, asl_basename), "w") as f:
        json.dump(doc, f, indent=2)

    class_name = args.class_name or (re.sub(r"[^A-Za-z0-9]", "", args.name) + "Stack")
    placeholders = _find_placeholders(doc)
    props_lines = [f"  readonly {p.lower()}: string;" for p in placeholders] or \
                  ["  // (no substitutions detected)"]
    subs_lines = [f"        {p}: props.{p.lower()}," for p in placeholders] or \
                 ["        // (no substitutions)"]

    policy = _infer_iam.infer_policy(doc, include_logging=True, include_xray=True)
    stmts_ts: list[str] = []
    for stmt in policy["Statement"]:
        actions = [a for a in stmt.get("Action", []) if not a.startswith("#")]
        if not actions:
            continue
        stmts_ts.append(
            f"    role.addToPolicy(new iam.PolicyStatement({{\n"
            f"      sid: {json.dumps(stmt.get('Sid', ''))},\n"
            f"      effect: iam.Effect.ALLOW,\n"
            f"      actions: {json.dumps(actions)},\n"
            f"      resources: [{json.dumps(stmt.get('Resource', '*'))}],\n"
            f"    }}));"
        )

    ts = (_TS_TEMPLATE
          .replace("%CLASS%", class_name)
          .replace("%NAME%", args.name)
          .replace("%ASL%", asl_basename)
          .replace("%TYPE%", args.type)
          .replace("%PROPS%", "\n".join(props_lines))
          .replace("%SUBS%", "\n".join(subs_lines))
          .replace("%POLICY%", "\n\n".join(stmts_ts) if stmts_ts else "    // (no IAM statements inferred)"))

    out_path = os.path.join(args.outdir, f"{class_name.lower()}.ts")
    with open(out_path, "w") as f:
        f.write(ts)

    print(f"wrote {out_path}")
    print(f"wrote {os.path.join(args.outdir, asl_basename)}")
    print(f"add to your CDK app: new {class_name}(app, '{args.name}Stack', {{ ... }})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
