#!/usr/bin/env python3
"""
Emit a Terraform scaffold that deploys a Step Functions state machine from an
externally authored ASL file. Uses aws_sfn_state_machine with templatefile()
so that DefinitionSubstitutions-style placeholders (${...}) can be filled in
from Terraform variables.

Usage:
    python scripts/deploy/emit_terraform.py \
        --asl path/to/workflow.asl.json \
        --name my-state-machine \
        --type STANDARD \
        --outdir terraform/
"""
from __future__ import annotations

import argparse
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(_HERE, "..")))

import _infer_iam  # noqa: E402


_TERRAFORM_TEMPLATE = r"""# Generated by aws-step-functions-jsonata skill.
# Review before applying. Docs: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sfn_state_machine

terraform {
  required_version = ">= 1.5"
  required_providers {
    aws = { source = "hashicorp/aws", version = ">= 5.0" }
  }
}

locals {
  name = "%NAME%"
  type = "%TYPE%"
}

resource "aws_cloudwatch_log_group" "sfn" {
  # /aws/vendedlogs/states/* bypasses the 5120-char per-log-group
  # resource-policy cap that affects other CloudWatch log group names.
  name              = "/aws/vendedlogs/states/${local.name}"
  retention_in_days = 14
}

resource "aws_iam_role" "sfn" {
  name = "${local.name}-execution-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "states.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy" "sfn_inline" {
  role   = aws_iam_role.sfn.id
  name   = "${local.name}-inline"
  policy = jsonencode(%POLICY_JSON%)
}

resource "aws_sfn_state_machine" "this" {
  name     = local.name
  role_arn = aws_iam_role.sfn.arn
  type     = local.type

  definition = templatefile("${path.module}/%ASL_BASENAME%", {
    # Fill in one entry per ${Placeholder} referenced in the ASL.
    # Example: ProcessingLambdaArn = aws_lambda_function.proc.arn
%SUBSTITUTIONS%
  })

  logging_configuration {
    log_destination        = "${aws_cloudwatch_log_group.sfn.arn}:*" # trailing :* required
    include_execution_data = true
    level                  = "ALL"
  }

  tracing_configuration { enabled = true }
}

output "state_machine_arn" {
  value = aws_sfn_state_machine.this.arn
}
"""


def _find_placeholders(doc: dict) -> list[str]:
    """Find unique ${Placeholder} tokens in the ASL for substitution hints."""
    import re
    tokens = set()
    pat = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")

    def walk(obj):
        if isinstance(obj, str):
            tokens.update(pat.findall(obj))
        elif isinstance(obj, dict):
            for v in obj.values():
                walk(v)
        elif isinstance(obj, list):
            for v in obj:
                walk(v)

    walk(doc)
    return sorted(tokens)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--asl", required=True)
    ap.add_argument("--name", required=True)
    ap.add_argument("--type", default="STANDARD", choices=["STANDARD", "EXPRESS"])
    ap.add_argument("--outdir", required=True)
    args = ap.parse_args(argv)

    with open(args.asl) as f:
        doc = json.load(f)

    os.makedirs(args.outdir, exist_ok=True)

    # Copy the ASL
    asl_basename = os.path.basename(args.asl)
    with open(os.path.join(args.outdir, asl_basename), "w") as f:
        json.dump(doc, f, indent=2)

    # Build substitution hints
    placeholders = _find_placeholders(doc)
    subs = "\n".join(f"    # {p} = ..." for p in placeholders) or "    # (no substitutions detected)"

    policy = _infer_iam.infer_policy(doc)
    # Strip comments that infer_policy adds for unknown resources — Terraform jsonencode
    # won't preserve them either way; ensure valid JSON.
    for stmt in policy.get("Statement", []):
        stmt.pop("Comment", None)
        stmt["Action"] = [a for a in stmt["Action"] if not a.startswith("#")]

    tf = (_TERRAFORM_TEMPLATE
          .replace("%NAME%", args.name)
          .replace("%TYPE%", args.type)
          .replace("%ASL_BASENAME%", asl_basename)
          .replace("%SUBSTITUTIONS%", subs)
          .replace("%POLICY_JSON%", json.dumps(policy, indent=2).replace("\n", "\n  ")))

    out_path = os.path.join(args.outdir, "state_machine.tf")
    with open(out_path, "w") as f:
        f.write(tf)

    print(f"wrote {out_path}")
    print(f"wrote {os.path.join(args.outdir, asl_basename)}")
    if placeholders:
        print(f"fill in the {len(placeholders)} placeholder substitution(s) in the locals block: "
              f"{', '.join(placeholders)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
